// packages/react/components/lib/Select.tsx
import "@potzblitz/styles/lib/components/Select.scss";
import React, { useState } from "react";
import { api } from "@potzblitz/components";

export function Select<T>(props: api.SelectProps<T>) {
  const [idStr, _id] = api.uniqueName(props.label);
  const [vO, setVO] = useState(props.value);
  const [showOptions, setShowOptions] = useState(false);

  const handleSelect = (option: T) => {
    const idx = props.options.indexOf(option);
    props.onSelect && props.onSelect(option, idx);
    setVO(idx);
    setShowOptions(false);
  };

  return (
    <div className="select" id={idStr}>
      {props.label && <label htmlFor={idStr}>{props.label}</label>}
      <div className="selected" onClick={() => setShowOptions(!showOptions)}>
        {props.displayFn
          ? props.displayFn(props.options[vO])
          : props.options[vO]}
      </div>
      <div className={["options", !showOptions && "hidden"].join(" ")}>
        {props.options
          .filter((o) => o !== props.options[vO])
          .map((option: T) => {
            return (
              <div
                key={option}
                className="option"
                onClick={() => handleSelect(option)}
              >
                {props.displayFn ? props.displayFn(option) : option}
              </div>
            );
          })}
      </div>
    </div>
  );
}

// packages/solid/components/lib/Select.tsx
import "@potzblitz/styles/lib/components/Select.scss";
import { SelectProps, uniqueName } from "@potzblitz/api";
import { For, mergeProps, createSignal, createEffect } from "solid-js";
import { CopyValueButton } from "./blocks";

export function Select<T>(props: SelectProps<T>) {
  const mprops: SelectProps<T> = mergeProps({ options: [], value: 0 }, props);
  const [idStr, _id] = uniqueName(mprops.label);
  const [vO, setVO] = createSignal<number>(mprops.value);
  const [showOptions, setShowOptions] = createSignal(false);

  createEffect(() => {
    setVO(mprops.value);
  });

  const handleSelect = (option: T) => {
    const idx = mprops.options.indexOf(option);
    props.onSelect && props.onSelect(option, idx);
    setVO(idx);
    setShowOptions(false);
  };

  const appylDisplayFn = (o: T): string =>
    mprops.displayFn !== undefined ? mprops.displayFn(o) : (o as string);

  return (
    <div class="select" id={idStr}>
      {props.label && <label for={idStr}>{mprops.label}</label>}
      <div class="selected" onClick={() => setShowOptions(!showOptions())}>
        {appylDisplayFn(mprops.options[vO()])}
      </div>
      <div classList={{ options: true, hidden: !showOptions() }}>
        <For
          each={mprops.options.filter((o) => o !== mprops.options[vO()])}
          fallback={<></>}
        >
          {(option: T, _: () => number) => {
            return (
              <div
                classList={{ option: true }}
                onclick={() => handleSelect(option)}
              >
                {appylDisplayFn(option)}
              </div>
            );
          }}
        </For>
      </div>
      {mprops.showCopyButton && <CopyValueButton value={vO()} />}
    </div>
  );
}
