// packages/react/components/lib/Slider.tsx
import "@potzblitz/styles/lib/components/Slider.scss";
import React, { useState, useEffect } from "react";
import { api } from "@potzblitz/components";
import { AdditionalValueInput } from "./blocks";

export function Slider(props: api.SliderProps) {
  const [idStr, _id] = api.uniqueName(props.label);
  const [vO, setVO] = useState<number>(props.value);

  useEffect(() => {
    setVO(props.value);
  }, [props.value]);

  const handleInput = (e: InputEvent): number => {
    const target = e.target as HTMLInputElement;
    const value = target.value;
    const newVO = parseFloat(value);
    setVO(newVO);
    return newVO;
  };

  return (
    <div className="slider" id={idStr}>
      {props.label && <label htmlFor={idStr}>{props.label}</label>}
      <input
        type="range"
        id={idStr}
        value={vO}
        min={props.min || 0}
        max={props.max || 100}
        step={props.step || 1}
        onInput={(e: InputEvent) => {
          const v = handleInput(e);
          props.onUpdate && props.onUpdate(v);
        }}
        onPointerUp={(e: InputEvent) => {
          const v = handleInput(e);
          props.onBlur && props.onBlur(v);
        }}
      />
      <AdditionalValueInput value={vO} />
    </div>
  );
}

// packages/solid/components/lib/Slider.tsx
import "@potzblitz/styles/lib/components/Slider.scss";
import { SliderProps, uniqueName } from "@potzblitz/api";
import { mergeProps, createSignal, createEffect } from "solid-js";
import { CopyValueButton, ValueView } from "./blocks";

export function Slider(props: SliderProps) {
  const mprops: SliderProps = mergeProps(
    {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
      onUpdate: () => {},
      onBlur: () => {},
      showCopyButton: false,
    },
    props,
  );

  const [idStr, _id] = uniqueName(mprops.label);
  const [vO, setVO] = createSignal(mprops.value);

  const handleInput = (e: InputEvent | PointerEvent): number => {
    const target = e.target as HTMLInputElement;
    const value = target.value;
    const newValue = parseFloat(value);
    setVO(newValue);
    return newValue;
  };

  createEffect(() => {
    setVO(mprops.value);
  });

  return (
    <div classList={{ slider: true, ...mprops.classList }} id={idStr}>
      {mprops.label && <label>{mprops.label}</label>}
      <div class="slider-wrap">
        <input
          type="range"
          value={vO()}
          min={mprops.min}
          max={mprops.max}
          step={mprops.step}
          onInput={(e: InputEvent) =>
            mprops.onUpdate && mprops.onUpdate(handleInput(e))
          }
          onPointerUp={(e: PointerEvent) =>
            mprops.onBlur && mprops.onBlur(handleInput(e))
          }
        />
        <ValueView value={vO()} />
      </div>
      {mprops.showCopyButton && <CopyValueButton value={vO()} />}
    </div>
  );
}
