// packages/components/src/react/Button.tsx
import "../scss/Button.scss";
import React from "react";
import { ButtonProps, camelCaseWithSpaces } from "../api";

export function Button(props: ButtonProps) {
  return (
    <button className="button" onClick={props.onClick}>
      {camelCaseWithSpaces(props.label ?? "Button")}
    </button>
  );
}

// packages/components/src/solid/Button.tsx
import "../scss/Button.scss";
import { mergeProps } from "solid-js";
import { ButtonProps, camelCaseWithSpaces } from "../api";

export function Button(props: ButtonProps) {
  const mprops = mergeProps({ label: "", onClick: () => {} }, props);
  return (
    <button class="button" onClick={props?.onClick}>
      {camelCaseWithSpaces(mprops.label)}
    </button>
  );
}
