// packages/react/components/lib/Toggle.tsx
import "@potzblitz/styles/lib/components/Toggle.scss";
import React, { useState, useEffect } from "react";
import { api } from "@potzblitz/components";

export function Toggle(props: api.ToggleProps) {
  const [vO, setVO] = useState<boolean>(props.value);

  useEffect(() => {
    setVO(props.value);
  }, [props.value]);

  const handleSwitch = () => {
    const newValue = !vO;
    setVO(newValue);
    props.onChange && props.onChange(newValue);
  };

  return (
    <div className="toggle">
      {props.label && <label>{api.camelCaseWithSpaces(props.label)}</label>}
      <div className="knob" onClick={handleSwitch}>
        <div className={["state", vO && "on"].join(" ")}>
          <input type="checkbox" value={vO} />
        </div>
      </div>
    </div>
  );
}

// packages/components/src/solid/Toggle.tsx
import "../scss/Toggle.scss";
import { camelCaseWithSpaces, ToggleProps } from "../api";
import { createSignal, mergeProps } from "solid-js";

export function Toggle(props: ToggleProps) {
  const mprops: ToggleProps = mergeProps(
    { value: false, onChange: () => {} },
    props
  );

  const [vO, setVO] = createSignal(props.value);

  const handleSwitch = () => {
    const newValue = !vO();
    setVO(newValue);
    mprops.onChange && mprops.onChange(newValue);
  };

  return (
    <div class="toggle">
      {mprops.label && <label>{camelCaseWithSpaces(mprops.label)}</label>}
      <div class="knob" onClick={handleSwitch}>
        <div classList={{ state: true, on: vO() }}>
          <input type="checkbox" value={vO()} />
        </div>
      </div>
    </div>
  );
}
