// packages/solid/components/lib/Button.tsx
import "@potzblitz/components/src/scss/Button.scss";
import { mergeProps } from "solid-js";
import {
  ButtonProps,
  camelCaseWithSpaces,
} from "@potzblitz/components/src/api";

export function Button(props: ButtonProps) {
  const mprops: ButtonProps = mergeProps(
    { label: "", onClick: () => {}, classList: {} },
    props
  );

  return (
    <div class="button-wrapper" classList={mprops.classList}>
      <button
        class="button"
        onClick={props?.onClick}
        disabled={mprops.disabled}
      >
        {camelCaseWithSpaces(mprops.label)}
      </button>
    </div>
  );
}

// packages/react-components/lib/Button.tsx
import "@potzblitz/components/src/scss/Button.scss";
import React from "react";
import { api } from "@potzblitz/components";

export function Button(props: api.ButtonProps) {
  return (
    <button className="button" onClick={props.onClick}>
      {api.camelCaseWithSpaces(props.label ?? "Button")}
    </button>
  );
}
