// packages/components/src/solid/Select.tsx
import "../scss/Select.scss";
import { SelectProps, uniqueName } from "../api";
import { For, mergeProps, createSignal } from "solid-js";
import { CopyValueButton } from "./blocks";

export function Select<T>(props: SelectProps<T>) {
  const mprops: SelectProps<T> = mergeProps({ options: [], value: 0 }, props);
  const [idStr, _id] = uniqueName(mprops.label);
  const [vO, setVO] = createSignal<number>(mprops.value);
  const [showOptions, setShowOptions] = createSignal(false);

  const handleSelect = (option: T) => {
    const idx = mprops.options.indexOf(option);
    props.onSelect && props.onSelect(idx);
    setVO(idx);
    setShowOptions(false);
  };

  return (
    <div class="select" id={idStr}>
      {props.label && <label for={idStr}>{mprops.label}</label>}
      <div class="selected" onClick={() => setShowOptions(!showOptions())}>
        {mprops.options[vO()]}
      </div>
      <div classList={{ options: true, hidden: !showOptions() }}>
        <For each={mprops.options} fallback={<></>}>
          {(option: T, _: () => number) => {
            return (
              <div
                classList={{
                  option: true,
                  hidden: option === mprops.options[vO()],
                }}
                onclick={() => handleSelect(option)}
              >
                {option}
              </div>
            );
          }}
        </For>
      </div>
      <CopyValueButton value={vO()} />
    </div>
  );
}

// packages/components/src/react/Select.tsx
import "../scss/Select.scss";
import React, { useState } from "react";
import { SelectProps, uniqueName } from "../api";

export function Select<T>(props: SelectProps<T>) {
  const [idStr, _id] = uniqueName(props.label);
  const [vO, setVO] = useState(props.value);
  const [showOptions, setShowOptions] = useState(false);

  const handleSelect = (option: T) => {
    const idx = props.options.indexOf(option);
    props.onSelect && props.onSelect(idx);
    setVO(idx);
    setShowOptions(false);
  };

  return (
    <div className="select" id={idStr}>
      {props.label && <label for={idStr}>{props.label}</label>}
      <div className="selected" onClick={() => setShowOptions(!showOptions)}>
        {props.options[vO]}
      </div>
      <div className={["options", !showOptions && "hidden"].join(" ")}>
        {props.options.map((option: T) => {
          return (
            <div
              className={[
                "option",
                option === props.options[vO] && "hidden",
              ].join(" ")}
              onClick={() => handleSelect(option)}
            >
              {option}
            </div>
          );
        })}
      </div>
    </div>
  );
}
