// packages/components/src/solid/Slider.tsx
import "../scss/Slider.scss";
import { mergeProps, createSignal, createEffect } from "solid-js";
import { SliderPros, uniqueName } from "../api";
import { CopyValueButton, AdditionalValueInput } from "./blocks";

export function Slider(props: SliderPros) {
  const mprops: SliderPros = mergeProps(
    {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
      onUpdate: () => {},
      onBlur: () => {},
    },
    props
  );

  const [idStr, _id] = uniqueName(mprops.label);
  const [vO, setVO] = createSignal(mprops.value);

  const handleInput = (e: InputEvent): number => {
    const target = e.target as HTMLInputElement;
    const value = target.value;
    const newValue = parseFloat(value);
    setVO(newValue);
    return newValue;
  };

  createEffect(() => {
    setVO(mprops.value);
  });

  return (
    <div className="slider" id={idStr}>
      {mprops.label && <label>{mprops.label}</label>}
      <input
        type="range"
        value={vO()}
        min={mprops.min}
        max={mprops.max}
        step={mprops.step}
        onInput={(e: InputEvent) => mprops.onUpdate(handleInput(e))}
        onPointerUp={(e: InputEvent) => mprops.onBlur(handleInput(e))}
      />
      <AdditionalValueInput value={vO()} />
      <CopyValueButton value={vO()} />
    </div>
  );
}

// packages/components/src/react/Slider.tsx
import "../scss/Slider.scss";
import React, { useState, useEffect } from "react";
import { SliderProps, uniqueName } from "../api";
import { AdditionalValueInput } from "./blocks";

export function Slider(props: SliderProps) {
  const [idStr, _id] = uniqueName(props.label);
  const [vO, setVO] = useState<number>(props.value);

  useEffect(() => {
    setVO(props.value);
  }, [props.value]);

  const handleInput = (e: InputEvent): number => {
    const target = e.target as HTMLInputElement;
    const value = target.value;
    const newVO = parseFloat(value);
    setVO(newVO);
    return newVO;
  };

  return (
    <div className="slider" id={idStr}>
      {props.label && <label htmlFor={idStr}>{props.label}</label>}
      <input
        type="range"
        id={idStr}
        value={vO}
        min={props.min || 0}
        max={props.max || 100}
        step={props.step || 1}
        onInput={(e: InputEvent) =>
          props.onUpdate && props.onUpdate(handleInput(e))
        }
        onPointerUp={(e: InputEvent) =>
          props.onBlur && props.onBlur(handleInput(e))
        }
      />
      <AdditionalValueInput value={vO} />
    </div>
  );
}
