// examples/solid/src/index.tsx
import "./index.scss";
import { render, For, Index } from "solid-js/web";
import { createStore } from "solid-js/store";
import {
  ColorPicker,
  ColorSelector,
  Slider,
  InputField,
} from "@potzblitz/components/src/solid";
import { createSignal } from "solid-js";

function App() {
  const [store, updateStore] = createStore({ v: 10 });
  const [sliders, updateSliders] = createSignal([0, 0, 0]);
  const [colors, updateColors] = createSignal(["", "", ""]);

  return (
    <div class="ui-root">
      <h1>Solid × Potzblitz</h1>
      <ColorPicker value="#ff0000" />
      <ColorSelector label="backgroundColor" value="#00ff00" />
      <Slider
        value={store["v"]}
        min={0}
        max={20}
        step={0.01}
        onUpdate={(v) => updateStore("v", v)}
      />
      <InputField value={store["v"]} min={0} max={20} step={0.01} />

      <Index each={colors()}>
        {(v, i) => {
          return (
            <div>
              <ColorSelector label={`color-${i}`} />
            </div>
          );
        }}
      </Index>

      <Index each={sliders()}>
        {(v, i) => {
          return (
            <div>
              <Slider
                label="Slider"
                value={v}
                onUpdate={(v: number) => {
                  const update = [...sliders()];
                  update[i] = v;
                  updateSliders(update);
                }}
              />
              <span>Value: {v}</span>
            </div>
          );
        }}
      </Index>
      <code>{JSON.stringify(sliders())}</code>

      <Index each={sliders()}>
        {(v, i) => {
          return (
            <div>
              <Slider
                label="Slider"
                value={v}
                onUpdate={(v: number) => {
                  const update = [...sliders()];
                  update[i] = v;
                  updateSliders(update);
                }}
              />
              <span>Value: {v}</span>
            </div>
          );
        }}
      </Index>
    </div>
  );
}

render(App, document.body);

// examples/react/src/index.tsx
import React, { useState, useEffect } from "react";
import { createRoot } from "react-dom/client";
import {
  Button,
  Slider,
  ColorPicker,
  ColorSelector,
} from "@potzblitz/react-components";
import "@potzblitz/styles";
import "./styles.scss";
import "@potzblitz/react-components/dist/style.css";

const componentMap = new Map<string, any>();
componentMap.set("number", Slider);
componentMap.set("function", Button);
componentMap.set("string", ColorSelector);

const ViewState = ({ state }) => <code>{JSON.stringify(state)}</code>;

function App() {
  const [state, updateState] = useState({
    slider: 0,
    save: () => alert("Save from Button!"),
    inputField: 10,
    color: "#ff0000",
  });

  return (
    <React.Fragment>
      <h1>React Potzblitz</h1>
      <div className="ui-root">
        {Object.keys(state).map((key: string) => {
          const value = state[key];
          const nativeType = typeof state[key];
          const Component = componentMap.get(nativeType) ?? (
            <span>No Component</span>
          );
          return (
            <div key={key}>
              <Component
                label={key}
                value={value}
                onClick={typeof value === "function" ? value : null}
                onUpdate={(v) => {
                  updateState((o) => {
                    const update = { ...o };
                    update[key] = v;
                    return update;
                  });
                }}
              />
            </div>
          );
        })}
      </div>

      <ViewState state={state} />
    </React.Fragment>
  );
}

const root = createRoot(document.querySelector(".mount"));
root.render(<App />);
