// packages/components/src/solid/Slider.tsx
import "../scss/Slider.scss";
import { mergeProps, createSignal, createEffect } from "solid-js";
import { SliderPros, uniqueName } from "../api";
import { CopyValueButton, ValueView } from "./blocks";

export function Slider(props: SliderPros) {
  const mprops: SliderPros = mergeProps(
    {
      value: 0,
      min: 0,
      max: 100,
      step: 1,
      onUpdate: () => {},
      onBlur: () => {},
      showCopyButton: false,
    },
    props
  );

  const [idStr, _id] = uniqueName(mprops.label);
  const [vO, setVO] = createSignal(mprops.value);

  const handleInput = (e: InputEvent): number => {
    const target = e.target as HTMLInputElement;
    const value = target.value;
    const newValue = parseFloat(value);
    setVO(newValue);
    return newValue;
  };

  createEffect(() => {
    setVO(mprops.value);
  });

  return (
    <div classList={{ slider: true, ...mprops.classList }} id={idStr}>
      {mprops.label && <label>{mprops.label}</label>}
      <input
        type="range"
        value={vO()}
        min={mprops.min}
        max={mprops.max}
        step={mprops.step}
        onInput={(e: InputEvent) =>
          mprops.onUpdate && mprops.onUpdate(handleInput(e))
        }
        onPointerUp={(e: InputEvent) =>
          mprops.onBlur && mprops.onBlur(handleInput(e))
        }
      />
      <ValueView value={vO()} />
      {mprops.showCopyButton && <CopyValueButton value={vO()} />}
    </div>
  );
}

// examples/solid/src/Slider.tsx
export function Slider(props: any) {
  const handleInput = (e: InputEvent): number => {
    const target = e.target as HTMLInputElement;
    const value = target.value;
    const newValue = parseFloat(value);
    return newValue;
  };

  return (
    <div classList={{ slider: true }}>
      {props.label && <label>{props.label}</label>}
      {/*      <input
           type="range"
           value={props.value}
           min={props.min}
           max={props.max}
           step={props.step}
           onInput={(e: InputEvent) =>
             props.onUpdate && props.onUpdate(handleInput(e))
                   }
           onPointerUp={(e: InputEvent) =>
             props.onBlur && props.onBlur(handleInput(e))
                       }
      />
       */}
      <button onClick={() => props.onUpdate(props.value + 1)}>
        {props.value}
      </button>
    </div>
  );
}
